// <auto-generated />
using FarmFreshAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmFreshAPI.Migrations
{
    [DbContext(typeof(ProductDetailContext))]
    partial class ProductDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FarmFreshAPI.Models.ProductDetail", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"), 1L, 1);

                    b.Property<string>("productAbout")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("productCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("productImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("productInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("productPacket")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("productQty")
                        .HasColumnType("int");

                    b.Property<string>("productSubName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("productId");

                    b.ToTable("ProductDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
